### Créer une réservation valide
POST http://localhost:8080/booking
Content-Type: application/json

{
  "clientName": "Jean AMrc",
  "phoneNumber": "0601020304",
  "email": "Jean@example.com",
  "roomNumber": 3,
  "roomDescription": "Chambre double vue mer",
  "reservationDate": "2025-09-05"
}

### Tenter de réserver la même chambre à la même date (→ 409 Conflict)
POST http://localhost:8080/booking
Content-Type: application/json

{
  "clientName": "Rakoto",
  "phoneNumber": "0611223344",
  "email": "bob@example.com",
  "roomNumber": 3,
  "roomDescription": "Chambre double vue mer",
  "reservationDate": "2025-09-05"
}

### Chambre hors intervalle (→ 400 Bad Request)
POST http://localhost:8080/booking
Content-Type: application/json

{
  "clientName": "Rasoa",
  "phoneNumber": "0622334455",
  "email": "charlie@example.com",
  "roomNumber": 15,
  "roomDescription": "Chambre inexistante",
  "reservationDate": "2025-09-10"
}

### Voir toutes les réservations
GET http://localhost:8080/booking